/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cumimpactsa;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;

/**
 *
 * @author ast
 */
public class ColorScaleDialog extends javax.swing.JDialog {

    /**
     * Creates new form ColorScaleDialog
     */
    public ColorScaleDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
  
        //display current color scale
        this.PanelColHigh.setBackground(ImageCreator.maxColor);
        this.PanelColMid.setBackground(ImageCreator.midColor);
        this.PanelColLow.setBackground(ImageCreator.minColor);

        ((ColorScalePanel) (this.colorScalePanel)).paintComponent(colorScalePanel.getGraphics());
        this.update(this.getGraphics());
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelColHigh = new javax.swing.JPanel();
        PanelColLow = new javax.swing.JPanel();
        PanelColMid = new javax.swing.JPanel();
        buttonOK = new javax.swing.JButton();
        colorScalePanel = new cumimpactsa.ColorScalePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        PanelColHigh.setBackground(new java.awt.Color(51, 51, 255));
        PanelColHigh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelColHighMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelColHighLayout = new org.jdesktop.layout.GroupLayout(PanelColHigh);
        PanelColHigh.setLayout(PanelColHighLayout);
        PanelColHighLayout.setHorizontalGroup(
            PanelColHighLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 68, Short.MAX_VALUE)
        );
        PanelColHighLayout.setVerticalGroup(
            PanelColHighLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 34, Short.MAX_VALUE)
        );

        PanelColLow.setBackground(new java.awt.Color(0, 51, 255));
        PanelColLow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelColLowMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelColLowLayout = new org.jdesktop.layout.GroupLayout(PanelColLow);
        PanelColLow.setLayout(PanelColLowLayout);
        PanelColLowLayout.setHorizontalGroup(
            PanelColLowLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 68, Short.MAX_VALUE)
        );
        PanelColLowLayout.setVerticalGroup(
            PanelColLowLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 34, Short.MAX_VALUE)
        );

        PanelColMid.setBackground(new java.awt.Color(51, 51, 255));
        PanelColMid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelColMidMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelColMidLayout = new org.jdesktop.layout.GroupLayout(PanelColMid);
        PanelColMid.setLayout(PanelColMidLayout);
        PanelColMidLayout.setHorizontalGroup(
            PanelColMidLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 68, Short.MAX_VALUE)
        );
        PanelColMidLayout.setVerticalGroup(
            PanelColMidLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 34, Short.MAX_VALUE)
        );

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        colorScalePanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                colorScalePanelComponentShown(evt);
            }
        });

        org.jdesktop.layout.GroupLayout colorScalePanelLayout = new org.jdesktop.layout.GroupLayout(colorScalePanel);
        colorScalePanel.setLayout(colorScalePanelLayout);
        colorScalePanelLayout.setHorizontalGroup(
            colorScalePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 86, Short.MAX_VALUE)
        );
        colorScalePanelLayout.setVerticalGroup(
            colorScalePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 176, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(PanelColHigh, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(PanelColMid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(PanelColLow, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(colorScalePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(10, 10, 10))
                    .add(buttonOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 182, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(33, 33, 33)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(PanelColHigh, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(32, 32, 32)
                        .add(PanelColMid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(36, 36, 36)
                        .add(PanelColLow, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(colorScalePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(10, 10, 10)
                .add(buttonOK))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_buttonOKActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        colorScalePanel.setup();
        colorScalePanel.update(colorScalePanel.getGraphics());
    }//GEN-LAST:event_formComponentShown

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
 
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

    }//GEN-LAST:event_formWindowGainedFocus

    private void PanelColHighMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelColHighMouseClicked
        Color newColor = JColorChooser.showDialog(this,"Choose color",ImageCreator.maxColor);
        if(newColor!=null) {
            ImageCreator.maxColor=newColor;
            this.PanelColHigh.setBackground(newColor);
            this.update(this.getGraphics());
        }
    }//GEN-LAST:event_PanelColHighMouseClicked

    private void PanelColMidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelColMidMouseClicked
        Color newColor = JColorChooser.showDialog(this,"Choose color",ImageCreator.midColor);
        if(newColor!=null) {
            ImageCreator.midColor=newColor;
            this.PanelColMid.setBackground(newColor);
            this.update(this.getGraphics());
        }
    }//GEN-LAST:event_PanelColMidMouseClicked

    private void PanelColLowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelColLowMouseClicked
        Color newColor = JColorChooser.showDialog(this,"Choose color",ImageCreator.minColor);
        if(newColor!=null) {
            ImageCreator.minColor=newColor;
            this.PanelColLow.setBackground(newColor);
            this.update(this.getGraphics());
        }
    }//GEN-LAST:event_PanelColLowMouseClicked

    private void colorScalePanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_colorScalePanelComponentShown
            colorScalePanel.paintComponent(colorScalePanel.getGraphics());
    }//GEN-LAST:event_colorScalePanelComponentShown

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorScaleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorScaleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorScaleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorScaleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ColorScaleDialog dialog = new ColorScaleDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelColHigh;
    private javax.swing.JPanel PanelColLow;
    private javax.swing.JPanel PanelColMid;
    private javax.swing.JButton buttonOK;
    private cumimpactsa.ColorScalePanel colorScalePanel;
    // End of variables declaration//GEN-END:variables
}
