/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cumimpactsa;

import javax.swing.DefaultListModel;

/**
 *
 * @author ast
 */
public class DataTypeDialog extends javax.swing.JDialog {

    /**
     * Creates new form DataTypeDialog
     */
    public DataTypeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //set up data layer list
        String[] stressorNames=GlobalResources.mappingProject.getStressorNames();
        String[] ecocompNames = GlobalResources.mappingProject.getEcocompNames();
        DefaultListModel model = new DefaultListModel();
        for(int i=0; i<stressorNames.length; i++) {model.addElement(stressorNames[i]);}
        for(int i=0; i<ecocompNames.length; i++) {model.addElement(ecocompNames[i]);}
        this.listDataLayers.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioButtonPoint = new javax.swing.JRadioButton();
        radioButtonLine = new javax.swing.JRadioButton();
        radioButtonPolygon = new javax.swing.JRadioButton();
        radioButtonSurface = new javax.swing.JRadioButton();
        radioButtonUnknown = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDataLayers = new javax.swing.JList();
        buttonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Spatial data set");

        jLabel2.setText("Data type");

        buttonGroup1.add(radioButtonPoint);
        radioButtonPoint.setText("Point");
        radioButtonPoint.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonPointItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radioButtonLine);
        radioButtonLine.setText("Line");
        radioButtonLine.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonLineItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radioButtonPolygon);
        radioButtonPolygon.setText("Polygon");
        radioButtonPolygon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonPolygonItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radioButtonSurface);
        radioButtonSurface.setText("Surface");
        radioButtonSurface.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonSurfaceItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radioButtonUnknown);
        radioButtonUnknown.setText("Unknown");
        radioButtonUnknown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonUnknownItemStateChanged(evt);
            }
        });

        listDataLayers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDataLayers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listDataLayersValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listDataLayers);

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(radioButtonLine)
                            .add(layout.createSequentialGroup()
                                .add(radioButtonPoint)
                                .add(32, 32, 32)
                                .add(radioButtonUnknown))
                            .add(radioButtonPolygon)
                            .add(radioButtonSurface)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 148, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(buttonOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 238, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 238, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 240, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel2)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(radioButtonPoint)
                    .add(radioButtonUnknown))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(radioButtonLine)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(radioButtonPolygon)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(radioButtonSurface)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 23, Short.MAX_VALUE)
                .add(buttonOK))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonOKActionPerformed

    private void listDataLayersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listDataLayersValueChanged
        if(this.listDataLayers.getSelectedValue()!=null)
        {
            String selected = (String) this.listDataLayers.getSelectedValue();
            SpatialDataLayer selectedLayer = GlobalResources.mappingProject.getDataLayerByName(selected);
            if(selectedLayer.getSpatialDataType().equals(GlobalResources.SPATIALDATATYPE_UNKNOWN)) {this.radioButtonUnknown.setSelected(true);}
            else if(selectedLayer.getSpatialDataType().equals(GlobalResources.SPATIALDATATYPE_POINT)) {this.radioButtonPoint.setSelected(true);}
            else if(selectedLayer.getSpatialDataType().equals(GlobalResources.SPATIALDATATYPE_LINE)) {this.radioButtonLine.setSelected(true);}
            else if(selectedLayer.getSpatialDataType().equals(GlobalResources.SPATIALDATATYPE_POLYGON)) {this.radioButtonPolygon.setSelected(true);}
            else if(selectedLayer.getSpatialDataType().equals(GlobalResources.SPATIALDATATYPE_SURFACE)) {this.radioButtonSurface.setSelected(true);}
        }
    }//GEN-LAST:event_listDataLayersValueChanged

    private void radioButtonPointItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonPointItemStateChanged
        if(radioButtonPoint.isSelected())
        {
            String selected = (String) this.listDataLayers.getSelectedValue();
            SpatialDataLayer selectedLayer = GlobalResources.mappingProject.getDataLayerByName(selected);
            if(selectedLayer!=null) selectedLayer.setSpatialDataType(GlobalResources.SPATIALDATATYPE_POINT);
        }
    }//GEN-LAST:event_radioButtonPointItemStateChanged

    private void radioButtonLineItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonLineItemStateChanged
       if(radioButtonLine.isSelected())
        {
            String selected = (String) this.listDataLayers.getSelectedValue();
            SpatialDataLayer selectedLayer = GlobalResources.mappingProject.getDataLayerByName(selected);
            if(selectedLayer!=null) selectedLayer.setSpatialDataType(GlobalResources.SPATIALDATATYPE_LINE);
        }
    }//GEN-LAST:event_radioButtonLineItemStateChanged

    private void radioButtonPolygonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonPolygonItemStateChanged
        if(radioButtonPolygon.isSelected())
        {
            String selected = (String) this.listDataLayers.getSelectedValue();
            SpatialDataLayer selectedLayer = GlobalResources.mappingProject.getDataLayerByName(selected);
            if(selectedLayer!=null) selectedLayer.setSpatialDataType(GlobalResources.SPATIALDATATYPE_POLYGON);
        }
    }//GEN-LAST:event_radioButtonPolygonItemStateChanged

    private void radioButtonSurfaceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonSurfaceItemStateChanged
        if(radioButtonSurface.isSelected())
        {
            String selected = (String) this.listDataLayers.getSelectedValue();
            SpatialDataLayer selectedLayer = GlobalResources.mappingProject.getDataLayerByName(selected);
            if(selectedLayer!=null) selectedLayer.setSpatialDataType(GlobalResources.SPATIALDATATYPE_SURFACE);
        }
    }//GEN-LAST:event_radioButtonSurfaceItemStateChanged

    private void radioButtonUnknownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonUnknownItemStateChanged
        if(radioButtonUnknown.isSelected())
        {
            String selected = (String) this.listDataLayers.getSelectedValue();
            SpatialDataLayer selectedLayer = GlobalResources.mappingProject.getDataLayerByName(selected);
            if(selectedLayer!=null) selectedLayer.setSpatialDataType(GlobalResources.SPATIALDATATYPE_UNKNOWN);
        }
    }//GEN-LAST:event_radioButtonUnknownItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataTypeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataTypeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataTypeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataTypeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DataTypeDialog dialog = new DataTypeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listDataLayers;
    private javax.swing.JRadioButton radioButtonLine;
    private javax.swing.JRadioButton radioButtonPoint;
    private javax.swing.JRadioButton radioButtonPolygon;
    private javax.swing.JRadioButton radioButtonSurface;
    private javax.swing.JRadioButton radioButtonUnknown;
    // End of variables declaration//GEN-END:variables
}
